baseURL = 'https://example.org/'
languageCode = 'es-es'
title = 'Mi Portfolio'
theme = []

[taxonomies]
  category = 'categories'
  tag = 'tags'
  skill = 'skills'

[params]
  description = 'Portfolio personal construido con Hugo'
